spring.application.name=BookingTour

# Tắt cache template - không cần restart khi sửa HTML
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:mysql://localhost:3306/booking_tour
spring.datasource.username=root
spring.datasource.password=123456a@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
image.path=/tmp/booking-tour/uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
avatar.path=src/main/resources/static/anh/user/
# messages.properties
spring.security.ui.password=Password
spring.security.ui.username=Username
spring.security.ui.login=Sign in
spring.security.ui.remember=Remember me
spring.security.ui.error=Invalid credentials
debug=false

logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
spring.jackson.serialization.fail-on-empty-beans=false
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.security.oauth2.client.registration.google.client-id=935517380380-7cm59nmk238dgmq2116bsa0o10lc5slg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.facebook.client-id=955972583635226
spring.security.oauth2.client.registration.facebook.client-secret=9ecf1d89a2045f016f3389d4b50fd3c9
spring.security.oauth2.client.registration.facebook.scope=public_profile,email

spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email

# Amadeus API
amadeus.api.key=wr7EGAmSiRQG2wMZPGNAf9RbAKbiNBoS
amadeus.api.secret=qMVXA4W9eqIXTcus
amadeus.api.base-url=https://test.api.amadeus.com

# VNPay Config
vnp.pay-url=${VNP_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnp.return-url=${VNP_RETURN_URL:http://localhost:8080/payment/vnpay-callback}
vnp.tmn-code=${VNP_TMN_CODE:1HDJ5TF3}
vnp.hash-secret=DBRU24476VMM3E3B85YAZOHY4MFMZDBB
vnp.api-url=${VNP_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}

# NewsAPI Config
news.api.token=f4576b6c4b744b5bbb4306309ade8ff1
